config/routes.rb
Rails.application.routes.draw do
  resources :order_parties
  resources :order_parties
  resources :defects
  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'auth/:provider/callback', to: 'sessions#create'
  get  'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  scope "(:locale)", locale: /en|zh/ do

    resources :items do  
        resources :photos, only: [:create, :destroy] do
          collection do
            post :create_general     #-> domain.com/orders/:id/acknowledge
            post :create_before     #-> domain.com/orders/:id/acknowledge
            post :create_after     #-> domain.com/orders/:id/acknowledge
            post :insert                #-> domain.com/orders/:id/acknowledge
          end
          member do
            put  :switch_printable     #-> domain.com/orders/:id/delete+photo
          end
        end
      end
      
    resources :defects
    resources :issues
    resources :defects
    resources :sources
    resources :districts
    resources :orders do  
        member do
          put :cancel         #-> domain.com/orders/:id/complete
          put :file        #-> domain.com/complaints/:id/escalate 
        end
        resource :downloadpdf, only: [:show] 
        resources :comments
        collection do
          match 'search' => 'orders#search', via: [:get, :post], as: :search
        end
        # collection { post :search, to: 'orders#search' }
        resources :photos, only: [:create, :destroy] do
          collection do
            post :create_general     #-> domain.com/orders/:id/acknowledge
            post :create_before     #-> domain.com/orders/:id/acknowledge
            post :create_after     #-> domain.com/orders/:id/acknowledge
            post :insert                #-> domain.com/orders/:id/acknowledge
          end
          member do
            put  :switch_printable     #-> domain.com/orders/:id/delete+photo
          end
        end
      end

     # mount Upmin::Engine => '/admin'
	 # root to: 'visitors#index' 
     root to: 'visitors#mos'
     get "customer_faq" => "visitors#faq"
     get "partner_faq"  => "visitors#faq2"
     get "about"  => "visitors#about"
     # devise_for :users
     # devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
     resources :users
        resources :orders do 
       collection do 
        get :open
      end
    end
  end
end

app/models/order_party.rb
class OrderParty < ActiveRecord::Base
  belongs_to :order
end

app/controllers/order_parties_controller.rb
class OrderPartiesController < ApplicationController
  before_action :set_order_party, only: [:show, :edit, :update, :destroy]

  # GET /order_parties
  # GET /order_parties.json
  def index
    @order_parties = OrderParty.all
  end

  # GET /order_parties/1
  # GET /order_parties/1.json
  def show
  end

  # GET /order_parties/new
  def new
    @order_party = OrderParty.new
    @order_party.order_id = params[:order_id]
  end

  # GET /order_parties/1/edit
  def edit
  end

  # POST /order_parties
  # POST /order_parties.json
  def create
    @order_party = OrderParty.new(order_party_params)

    respond_to do |format|
      if @order_party.save
        format.html { redirect_to order_url(@order_party.order_id), notice: 'party was successfully created.' }
        format.json { render :show, status: :created, location: @order_party }
      else
        format.html { render :new }
        format.json { render json: @order_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_parties/1
  # PATCH/PUT /order_parties/1.json
  def update
    respond_to do |format|
      if @order_party.update(order_party_params)
        format.html { redirect_to @order_party, notice: 'Order party was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_party }
      else
        format.html { render :edit }
        format.json { render json: @order_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_parties/1
  # DELETE /order_parties/1.json
  def destroy
    @order_party.destroy
    respond_to do |format|
      format.html { redirect_to order_url(@order_party.order_id), notice: 'party was successfully created.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_party
      @order_party = OrderParty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_party_params
      params.require(:order_party).permit(:order_id, :name, :designation, :organization)
    end
end

app/helpers/order_parties_helper.rb
module OrderPartiesHelper
end

app/views/order_parties/_form.html.erb
<div class="container">
  <%= simple_form_for(@order_party) do |f| %>

  <br>
    <div class="form-inputs">
      <%#= f.association :order %>
      <%= f.input :order_id, :value => params[:order_id] %>

        <div class="row">
            <div class="col-xs-12 col-md-4 ">
              <%= f.input :name , label: t("name")%>
            </div>
            <div class="col-xs-12 col-md-4 ">
              <%= f.input :designation , label: t("designation")%>
            </div>
            <div class="col-xs-12 col-md-4 ">
              <%= f.input :organization , label: t("organization")%>
            </div>
        </div>

    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/order_parties/edit.html.erb
<%= render 'form' %>

app/views/order_parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Parties</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Name</th>
      <th>Designation</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_parties.each do |order_party| %>
      <tr>
        <td><%= order_party.order %></td>
        <td><%= order_party.name %></td>
        <td><%= order_party.designation %></td>
        <td><%= order_party.organization %></td>
        <td><%= link_to 'Show', order_party %></td>
        <td><%= link_to 'Edit', edit_order_party_path(order_party) %></td>
        <td><%= link_to 'Destroy', order_party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order party', new_order_party_path %>

app/views/order_parties/new.html.erb
<h1>New Order Party</h1>

<%= render 'form' %>

<%= link_to 'Back', order_parties_path %>

app/views/order_parties/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @order_party.name %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @order_party.designation %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @order_party.organization %>
</p>

  <%= link_to order_path(@order_party.order_id)  do %>
    <i class="glyphicon glyphicon-backward"></i>
  <% end %>
  <%= link_to edit_order_party_path(@order_party)  do %>
    <i class="glyphicon glyphicon-edit"></i>
  <% end %>
  <%= link_to @order_party, method: :delete, data: { confirm: 'Are you sure?' } do %>
    <i class="glyphicon glyphicon-trash"></i>
  <% end %>