config/routes.rb
Rails.application.routes.draw do
  resources :order_parties
  resources :order_parties
  resources :defects
  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'auth/:provider/callback', to: 'sessions#create'
  get  'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  scope "(:locale)", locale: /en|zh/ do

    resources :items do  
        resources :photos, only: [:create, :destroy] do
          collection do
            post :create_general     #-> domain.com/orders/:id/acknowledge
            post :create_before     #-> domain.com/orders/:id/acknowledge
            post :create_after     #-> domain.com/orders/:id/acknowledge
            post :insert                #-> domain.com/orders/:id/acknowledge
          end
          member do
            put  :switch_printable     #-> domain.com/orders/:id/delete+photo
          end
        end
      end
      
    resources :defects
    resources :issues
    resources :defects
    resources :sources
    resources :districts
    resources :orders do  
        member do
          put :cancel         #-> domain.com/orders/:id/complete
          put :file        #-> domain.com/complaints/:id/escalate 
        end
        resource :downloadpdf, only: [:show] 
        resources :comments
        collection do
          match 'search' => 'orders#search', via: [:get, :post], as: :search
        end
        # collection { post :search, to: 'orders#search' }
        resources :photos, only: [:create, :destroy] do
          collection do
            post :create_general     #-> domain.com/orders/:id/acknowledge
            post :create_before     #-> domain.com/orders/:id/acknowledge
            post :create_after     #-> domain.com/orders/:id/acknowledge
            post :insert                #-> domain.com/orders/:id/acknowledge
          end
          member do
            put  :switch_printable     #-> domain.com/orders/:id/delete+photo
          end
        end
      end

     # mount Upmin::Engine => '/admin'
	 # root to: 'visitors#index' 
     root to: 'visitors#mos'
     get "customer_faq" => "visitors#faq"
     get "partner_faq"  => "visitors#faq2"
     get "about"  => "visitors#about"
     # devise_for :users
     # devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
     resources :users
        resources :orders do 
       collection do 
        get :open
      end
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base  
  include AASM
  #before_action :is_authorised, only: [:photo_upload]

  belongs_to :user
#  belongs_to :district
  belongs_to :issue      
  has_many :items
  has_many :photos, as: :photoable, dependent: :destroy
  has_many :order_parties, inverse_of: :order, dependent: :destroy
  # after_save :create_notification
  before_create :set_orderno 
  # before_save :set_dates 

  default_scope { order('booking_datetime DESC') }

  scope :Due, -> { where(is_due: true)}
  scope :history, -> { where(role: :manager)}
  scope :history, lambda{ where("repair_datetime < ?", Date.today) }

  validates_presence_of :booking_datetime,  :status, :issue_id, :user_ref

  enum status: {Open: 0, Cancelled: 2, Filed: 13}

  aasm(:status) do
    state :Open, :initial => true

    state :Cancelled, :Filed

    event :cancel do
      transitions :from => :Open, :to => :Cancelled
    end

    event :file do
      transitions :from => :Open, :to => :Filed
    end

  end

  def self.i18n_statuses(hash = {})
    statuses.keys.each { |key| hash[I18n.t("statuses.#{key}")] = key }
    hash
  end

  def self.details(job_id)
    statuses.keys.each { |key| hash[I18n.t("statuses.#{key}")] = key }
    hash
  end

  def is_due
    self.deadline >= Date.today
  end

  def report_deadline
    #if self.completion_datetime?
    self.report_deadline_datetime
    #  self.completion_datetime.days_ago(self.report_duration * -1 ) 
    #end
  end

  private  
  def set_orderno
    max_code = Order.maximum(:order_no)
    cur_year = Date.current.year - 2000 
    if max_code.to_i > cur_year * 100000
      self.order_no = max_code.to_i + 1
    else 
      self.order_no = cur_year * 100000 + 1
    end
    max_ref_no = Order.where(" user_ref = ? ", self.user_ref).count + 1
    #max_ref_no = Order..where('user_id = ?', current_user.id).count + 1
    self.user_ref_no = max_ref_no
  end
      
  def is_authoorised
    redirect_to root_path, alert: "You don't have the permission"
      unless current_user.Manager? or current_user.Operator? or
        current_user.id == @order.technician_id
    end
  end

  def set_dates
    if self.status_changed?
      if self.Completed? 
        self.completion_datetime = Time.now 
      end 
      if self.InProgress?
        self.acknowledge_datetime = Time.now 
      end
    end 

    if self.completion_datetime_changed? and self.InProgress?
      # self.report_deadline_datetime = self.completion_datetime.days_ago(self.report_duration * -1 )
      self.complete!
    end 
    if self.completion_report_datetime_changed? and self.Completed?
        self.report!
    end 
    if self.appraisal_datetime_changed? and self.Reported?
        self.appraise!
    end 
  end

  def create_notification
    if self.worker_id_changed? and self.worker_id?
      #Notification.create(content: "請注意，一個新工作已分配給您.", user_id: self.worker_id)
      #OrderMailer.order_to_worker(self.id).deliver_now
    end
    if self.contractor_id_changed? and self.contractor_id?
      #Notification.create(content: "請注意，一個新工作已分配給您.", user_id: self.contractor_id)
      #OrderMailer.order_to_contractor(self.id).deliver_now
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  #before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_order, only: [:show, :edit, :update, :destroy,
          :cancel, :acknowledge, :file, :complete, :reopen, :downloadimages]

  def cancel
    @order.cancel!
    redirect_to orders_path(:status => "Open")
  end

  def file
    @order.file!
    #OrderMailer.new_order_to_authority(@order).deliver_now 
    redirect_to order_path(@order)
  end

  def downloadimages
    archiveFolder = Rails.root.join('tmp/archive.zip') #Location to save the zip
    # Delte .zip folder if it's already there
    FileUtils.rm_rf(archiveFolder)    
    #Zip::File.open("images_#{self.id}.zip", Zip::File::CREATE) do |zipfile|
    Zip::File.open(archiveFolder, Zip::File::CREATE) do |zipfile|
      @order.photos.each do |photo|
          open("tmp/image_#{photo.id}", 'wb') do |file|
            file << open("#{photo.image}").read
            # Two arguments:
            #filename = photo.id.to_s + ".jpg" 
            extension = File.extname("#{photo.image}") 
            filename = photo.id.to_s + extension 
            # - The name of the file as it will appear in the archive
            # - The original file, including the path to find it
            zipfile.add(filename, file)
          end
      end
    end
    # Send the archive as an attachment
    send_file(archiveFolder, :type => 'application/zip', :filename => 'images.zip', :disposition => 'attachment')
  end
# GET /orders
# GET /orders.json
    def search
      @q = Order.search(params[:q])
      @results = @q.result
      @results = @results.where(" booking_datetime >= ? ", Date.today ) unless params[:q]
      @orders = @results.page(params[:page]).per_page(50)
      respond_to do |format|
        format.html
      end
    end

  # GET /orders
  # GET /orders.json
  def index
    if params[:status] 
      case params[:status]
        when "Open"
          @orders = Order.Open
        when "Filed"
          @orders = Order.Filed 
        when "Cancelled" 
          @orders = Order.Cancelled
        when "All" 
          @orders = Order.all
        else
          @orders = Order.all
        end
        @orders = @orders.page(params[:page]).per_page(30)
    else
        if params[:commit] == "Search"
          @search = Order.search(params[:q])
          @results = @search.result
          if params[:format] == "xls"
            @orders = @results
          else
            @results = @results.where(" bookling_datetime >= ? ", Date.yesterday ) unless params[:q]
            @orders = @results
          end
        else
          @orders = Order.all
        end
    end

    if !current_user.Admin? 
      @orders = @orders.where('user_id = ?', current_user.id)
    end 
    @orders = @orders.order(created_at: :desc).paginate(page:params[:page], per_page: 20 )
    
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    respond_to do |format|
        format.html 
        format.pdf do
          pdf = OrderPdf.new(@order)
          send_data pdf.render, filename: "NF_#{@order.order_no}.pdf",
                                type: "application/pdf",
                                disposition: "inline"
        end 
      end

  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit

  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.booking_datetime = DateTime.now if @order.booking_datetime.nil?
    @order.user = current_user

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update

    respond_to do |format|
      # if @order.update(order_params)
      if @order.update_attributes(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
      @photoable = @order
      @photos = @photoable.photos 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:store_id, :user_id, :technician_id, 
        :booking_datetime, :district_id, :status, :issue_id, :user_ref, :notes, 
        :staff_name, :staff_signoff_date, :customer_name, :customer_signoff_date,
        :staff_signoff_datetime, :customer_signoff_datetime,
        :location, :source_ref, :order_no)
    end
end

app/views/orders/_form_m.html.erb
<div class="container">
  <br>
  <%= simple_form_for(@order) do |f| %>

    <div class="form-inputs"> 

      <div class="row">
          <div class="col-xs-12 col-md-4 ">
            <%= f.association :issue, :label => t("issue") %>
          </div>
          <div class="col-xs-12 col-md-6 ">
            <%= f.input :booking_datetime,  label: t("booking_date") %>
          </div>
          <div class="col-xs-12 col-md-2 ">
            <strong><%= t("order_no") %></strong><br><%= @order.order_no %>
          </div>
      </div>

      <div class="row">
          <div class="col-xs-12 col-md-4 ">
            <%= f.input :user_ref, label: t("user_ref") %>
          </div>
          <div class="col-xs-12 col-md-4">
            <%= f.input :location, :label => t("location") %>
          </div>
          <div class="col-xs-12 col-md-4">
            <%= f.input :status, collection: Order.i18n_statuses %>
          </div>
      </div><br>

      <div class="row">
          <div class="col-xs-12 col-md-8 ">
            <%= f.input :staff_name, label: t("staff_name") %>
          </div>
          <div class="col-xs-12 col-md-4">
            <%= f.input :staff_signoff_datetime,  as:  :datetime_picker, :label => t("staff_signoff_date") %>
          </div>
      </div><br>

      <div class="row">
          <div class="col-xs-12 col-md-8 ">
            <%= f.input :customer_name, label: t("customer_name") %>
          </div>
          <div class="col-xs-12 col-md-4">
            <%= f.input :customer_signoff_datetime,  as:  :datetime_picker, :label => t("customer_signoff_date") %>
          </div>
      </div><br>
      <div>
        <%= f.input :notes, :placeholder => t("remarks"), label: false %>
      </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>

</div>

  <% end %>

  <br>
  <%= link_to @order  do %>
      <i class="glyphicon glyphicon-zoom-in"></i>
  <% end %>
  <%= link_to orders_path  do %>
    <i class="glyphicon glyphicon-list"></i>
  <% end %>
</div>

app/views/orders/_index_pc.html.erb
<div class="container">
  <div class="row">
    <%= link_to t('OpenReports'), orders_path(:status => "Open"), class: 
          "btn btn-tab btn-light btn-tab btn-lg col  col-md-3"  %>  
    <%= link_to t('FiledReports'), orders_path(:status => "Filed"), class: 
          "btn btn-tab btn-success btn-tab btn-lg col  col-md-3"  %> 
    <%= link_to t('CancelledReports'), orders_path(:status => "Cancelled"), class: 
          "btn btn-tab btn-warning btn-tab btn-lg col  col-md-3"  %> 
    <%= link_to t('AllReports'), orders_path(:status => "All"), class: 
          "btn btn-tab btn-info btn-tab btn-lg col  col-md-3"  %> 
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t("order_no") %></th>
        <th><%= t("booking_date") %></th>
        <th><%= t("user_ref") %></th> 
        <th><%= t("user_ref_no") %></th> 
        <th><%= t("issue") %></th> 
        <th><%= t("location") %></th>
        <th><%= t("staff_name") %></th>
        <th><%= t("Sign_Date") %></th>
        <th><%= t("status") %></th>

      </tr>
    </thead>

    <tbody>
    <% if @orders.count > 0 %>
      <% @orders.each do |order| %>
        <tr class="info" data-link="<%= order_path(order) %>">
          <td><%= order.order_no %></td>
          <td><%= order.booking_datetime.strftime("%Y-%m-%d") if order.booking_datetime? %></td>
          <td><%= order.user_ref %></td>
          <td><%= order.user_ref_no %></td>
          <td><%= order.issue.display_name %></td>
          <td><%= order.location %></td>
          <td><%= order.staff_name %></td> 
          <td><%= order.staff_signoff_datetime.strftime("%Y-%m-%d") if order.staff_signoff_datetime? %></td> 
          <td><%= t(order.status) %></td> 
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @orders, :previous_label => '< ', :next_label => ' >' %>
  <br>

  <%= link_to new_order_path  do %>
          <i class="glyphicon glyphicon-plus"></i>
  <% end %>

app/views/orders/_photo_archived.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <!--    
      <div class="panel-heading">
        Photos
      </div>
      -->

      <div style="padding:0" class="panel-body">
        <div style="padding:0" class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="text-center">
                    <span class="btn btn-info  text-babu">
                       <i class="fa fa-camera" aria-hidden="true"></i> <%= t("Archive") %>
                     </span>
              <!-- Phgotos upload goes here -->
              </div>
            </div>
          </div>

            <div id="archived_photos"><%= render 'photos/order_not_printable_photos' %> </div>

        </div>
      </div>

    </div>
  </div>

</div>

app/views/orders/_photo_upload.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <!--    
      <div class="panel-heading">
        Photos
      </div>
      -->

      <div style="padding:0" class="panel-body">
        <div style="padding:0" class="container"> 
          <div class="row">
            <div class="col-md-12">
              <!-- Phgotos upload goes here -->
              <%= form_for @order, url: create_general_order_photos_path(@order), method: 'post',
                  html: {multipart: true} do |f| %>

                 <div class="text-center">
                   <div class="form-group">

                     <span class="btn btn-info  text-babu">
                       <i class="fa fa-camera" aria-hidden="true"></i> <%= t("photos") %>
                       <% if @order.Open? or current_user.Admin? %>
                        <%= file_field_tag "images[]", type: :file, multiple: true %>
                       <% end %>
                     </span>
                   </div>
                 </div>

                <% if @order.Open? or current_user.Admin? %>
                  <div class="text-center">
                    <%= button_tag type: 'submit', class: "btn btn-primary" do %><%= t("upload") %>
                        <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                    <% end %>
                  </div>
                <% end %>
 

              <% end %>
            </div>
          </div>

            <div id="uploaded_photos"><%= render 'photos/order_photos' %> </div>

        </div>
      </div>

    </div>
  </div>

</div>

app/views/orders/_show_m.html.erb
<br>
<div class="container">
  
  <div class="row">
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("user_ref") %>:</strong> <%= @order.user_ref %>
    </div>
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("user_ref_no") %>:</strong>    <%= @order.user_ref_no %>
    </div>
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("order_no") %>:</strong>    <%= @order.order_no %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("issue") %>:</strong>    <%= @order.issue.display_name %>
    </div>
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("inspection_date") %>:</strong> <%= @order.booking_datetime.strftime("%F %I:%M %P") %>
    </div>
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("status") %>:</strong>    
      <strong  style="color: red;" ><%= t(@order.status) %></strong>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-12 ">
      <strong><%= t("location") %>:</strong> <%= @order.location %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-12 ">
     <strong><%= t("remarks") %>:</strong>    <%= @order.notes %>
    </div>
  </div><br>

 <strong><%= t("relevant_parties") %></strong>
 <div class="container-fluid" style="border:1px solid #cecece;" >
    <% if @order.order_parties.present? %>
      <table id="stock_items" class="table table-striped">
        <thead>
        </thead> 
        <tbody>
          <% @order.order_parties.each do |order_party| %>          
            <tr  data-link="<%= order_party_path(order_party, order_id: order_party.order_id) %>"> 
               <td><p><%=  order_party.name %>  
                      <%=  order_party.designation  %>
                      <%=  order_party.organization  %></p></td>
            </tr>
            </tr> 
          <% end %>
        </tbody>
      </table>
    <% end %>
    <%= link_to new_order_party_path(order_id: @order)  do %>
            <i class="glyphicon glyphicon-plus"></i>
    <% end %>
  </div><br>

 <strong><%= t("issue") %></strong>
 <div class="container-fluid" style="border:1px solid #cecece;" >
    <% if @order.items.present? %>
      <table id="stock_items" class="table table-striped">
        <thead>
        </thead> 
        <tbody>
          <% @order.items.order(:due_date).each do |item | %>          
            <tr  data-link="<%= item_path(item, order_id: item.order_id) %>"> 
               <td><p><%=  item.defect.short_name  %></p> <%=  item.location  %></td>
               <td><p><%=  item.due_date.strftime("%Y-%m-%d") if item.due_date?   %> 
                <%=  item.responsible_person  %></p>
                <%=  item.completion_date.strftime("%Y-%m-%d") if item.completion_date?   %>  </td>
              </tr>
            </tr> 
          <% end %>
        </tbody>
      </table>
    <% end %>
    <%= link_to new_item_path(order_id: @order)  do %>
            <i class="glyphicon glyphicon-plus"></i>
    <% end %>
  </div>


<br><br>
  <div class="row">
    <div class="col-xs-6 col-md-6 ">
      <strong><%= t("staff_name") %>:</strong>    <%= @order.staff_name %>
    </div>
    <div class="col-xs-6 col-md-6 ">
      <strong><%= t("customer_name") %>:</strong>    <%= @order.customer_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-md-6 ">
      <strong><%= t("staff_signoff_date") %>:</strong> 
      <%= @order.staff_signoff_datetime.strftime("%F") if @order.staff_signoff_datetime  %>
    </div>
    <div class="col-xs-6 col-md-6 ">
      <strong><%= t("customer_signoff_date") %>:</strong> 
      <%= @order.customer_signoff_datetime.strftime("%F") if @order.customer_signoff_datetime %>
    </div>
  </div>


  <br>
  <div class="container">
    <div class="row">
    <%= link_to t('edit'), edit_order_path(@order), class: "btn btn-tall btn-warning col-xs-4 col-md-4"  %>  
    <%= link_to t('file'), file_order_path(@order), method: :put, class: "btn btn-tall btn-success col-xs-4 col-md-4"  %>  
    <%= link_to t('cancel'), cancel_order_path(@order), method: :put, class: "btn btn-tall btn-danger col-xs-4 col-md-4"  %>  
    </div>
  </div><br>

  <br><br>

  <%= render 'photo_upload' %>
</div>
  <div id="map" style="width: 100%; height: 100%"></div>
  <div id="photo_details"><%= render 'photos/order_photo_details' %> </div>

<script>
  function initialize() {
    var location = {lat: 22.300, lng: 114.18828}


    var map = new google.maps.Map(document.getElementById('map'), {
      center: location,
      zoom: 11
    });

    <% @order.photos.any? do  %>
      <% @order.photos.each do |photo| %>
        <% if photo.latitude.present? %>
          new google.maps.Marker({
            position: {lat: <%= photo.latitude %>, lng: <%= photo.longitude %> },
            map: map
          })
        <% end %> 
      <% end %>
    <% end %>

  }

  google.maps.event.addDomListener(window, 'load', initialize);

</script>

app/views/orders/_show_pc.html.erb
<br>
<div class="container">
  
  <div class="row">
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("user_ref") %>:</strong> <%= @order.user_ref %>
    </div>
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("user_ref_no") %>:</strong>    <%= @order.user_ref_no %>
    </div>
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("order_no") %>:</strong>    <%= @order.order_no %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("issue") %>:</strong>    <%= @order.issue.display_name %>
    </div>
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("inspection_date") %>:</strong> <%= @order.booking_datetime.strftime("%F %I:%M %P") %>
    </div>
    <div class="col-xs-12 col-md-4 ">
      <strong><%= t("status") %>:</strong>    
      <strong  style="color: red;" ><%= t(@order.status) %></strong>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-12 ">
      <strong><%= t("location") %>:</strong> <%= @order.location %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-12 ">
     <strong><%= t("remarks") %>:</strong>    <%= @order.notes %>
    </div>
  </div><br>

 <strong><%= t("relevant_parties") %></strong>
 <div class="container-fluid" style="border:1px solid #cecece;" >
    <% if @order.order_parties.present? %>
      <table id="stock_items" class="table table-striped">
        <thead>
          <tr>
            <th ><%= t("name") %></th>
            <th ><%= t("designation") %></th>
            <th ><%= t("organization") %></th> 
          </tr>
        </thead> 

        <tbody>

          <% @order.order_parties.each do |order_party | %>
 
            
            <tr  data-link="<%= order_party_path(order_party, order_id: order_party.order_id) %>"> 
               <td><%=  order_party.name  %></td>
               <td><%=  order_party.designation  %></td>
               <td><%=  order_party.organization  %></td>
              </tr>
            </tr> 
          <% end %>
        </tbody>
      </table>
    <% end %>
    <%= link_to new_order_party_path(order_id: @order)  do %>
            <i class="glyphicon glyphicon-plus"></i>
    <% end %>
  </div>
<br> 
 <strong><%= t("issue") %></strong>
 <div class="container-fluid" style="border:1px solid #cecece;" >
    <% if @order.items.present? %>
      <table id="stock_items" class="table table-striped">
        <thead>
          <tr>
            <th ><%= t("defect") %></th>
            <th ><%= t("location") %></th>
            <th ><%= t("followup") %></th>
            <th ><%= t("due_date") %></th>  
            <th ><%= t("completion_date") %></th>  
            <th ><%= t("responsible_person") %></th>  

          </tr>
        </thead> 

        <tbody>

          <% @order.items.order(:due_date).each do |item | %>
 
            
            <tr  data-link="<%= item_path(item, order_id: item.order_id) %>"> 
               <td><%=  item.defect.display_name  %></td>
               <td><%=  item.location  %></td>
               <td><%=  item.followup  %></td>
               <td><%=  item.due_date.strftime("%Y-%m-%d") if item.due_date?   %></td>
               <td><%=  item.completion_date.strftime("%Y-%m-%d") if item.completion_date?   %></td>
               <td><%=  item.responsible_person  %></td>
              </tr>
            </tr> 
          <% end %>
        </tbody>
      </table>
    <% end %>
    <%= link_to new_item_path(order_id: @order)  do %>
            <i class="glyphicon glyphicon-plus"></i>
    <% end %>
  </div>

<br>
  <div class="row">
    <div class="col-xs-6 col-md-6 ">
      <strong><%= t("staff_name") %>:</strong>    <%= @order.staff_name %>
    </div>
    <div class="col-xs-6 col-md-6 ">
      <strong><%= t("customer_name") %>:</strong>    <%= @order.customer_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-md-6 ">
      <strong><%= t("staff_signoff_date") %>:</strong> 
      <%= @order.staff_signoff_datetime.strftime("%F") if @order.staff_signoff_datetime  %>
    </div>
    <div class="col-xs-6 col-md-6 ">
      <strong><%= t("customer_signoff_date") %>:</strong> 
      <%= @order.customer_signoff_datetime.strftime("%F") if @order.customer_signoff_datetime %>
    </div>
  </div>


  <br>
  <div class="container">
    <div class="row">
    <%= link_to t('edit'), edit_order_path(@order), class: "btn btn-tall btn-warning col-xs-4 col-md-4"  %>  
    <%= link_to t('file'), file_order_path(@order), method: :put, class: "btn btn-tall btn-success col-xs-4 col-md-4"  %>  
    <%= link_to t('cancel'), cancel_order_path(@order), method: :put, class: "btn btn-tall btn-danger col-xs-4 col-md-4"  %>  
    </div>
  </div><br>

    <td>
      <%= link_to order_downloadpdf_path(@order, format: "pdf") do %>
        <i class="glyphicon glyphicon-download-alt fa-2x " style="color:blue" ></i>
      <% end %>
    </td>

  <br><br>

  <%= render 'photo_upload' %>
</div>
  <div id="map" style="width: 100%; height: 100%"></div>
  <div id="photo_details"><%= render 'photos/order_photo_details' %> </div>

<script>
  function initialize() {
    var location = {lat: 22.300, lng: 114.18828}


    var map = new google.maps.Map(document.getElementById('map'), {
      center: location,
      zoom: 11
    });

    <% @order.photos.any? do  %>
      <% @order.photos.each do |photo| %>
        <% if photo.latitude.present? %>
          new google.maps.Marker({
            position: {lat: <%= photo.latitude %>, lng: <%= photo.longitude %> },
            map: map
          })
        <% end %> 
      <% end %>
    <% end %>

  }

  google.maps.event.addDomListener(window, 'load', initialize);

</script>