config/routes.rb
Rails.application.routes.draw do
  resources :order_parties
  resources :order_parties
  resources :defects
  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'auth/:provider/callback', to: 'sessions#create'
  get  'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  scope "(:locale)", locale: /en|zh/ do

    resources :items do  
        resources :photos, only: [:create, :destroy] do
          collection do
            post :create_general     #-> domain.com/orders/:id/acknowledge
            post :create_before     #-> domain.com/orders/:id/acknowledge
            post :create_after     #-> domain.com/orders/:id/acknowledge
            post :insert                #-> domain.com/orders/:id/acknowledge
          end
          member do
            put  :switch_printable     #-> domain.com/orders/:id/delete+photo
          end
        end
      end
      
    resources :defects
    resources :issues
    resources :defects
    resources :sources
    resources :districts
    resources :orders do  
        member do
          put :cancel         #-> domain.com/orders/:id/complete
          put :file        #-> domain.com/complaints/:id/escalate 
        end
        resource :downloadpdf, only: [:show] 
        resources :comments
        collection do
          match 'search' => 'orders#search', via: [:get, :post], as: :search
        end
        # collection { post :search, to: 'orders#search' }
        resources :photos, only: [:create, :destroy] do
          collection do
            post :create_general     #-> domain.com/orders/:id/acknowledge
            post :create_before     #-> domain.com/orders/:id/acknowledge
            post :create_after     #-> domain.com/orders/:id/acknowledge
            post :insert                #-> domain.com/orders/:id/acknowledge
          end
          member do
            put  :switch_printable     #-> domain.com/orders/:id/delete+photo
          end
        end
      end

     # mount Upmin::Engine => '/admin'
	 # root to: 'visitors#index' 
     root to: 'visitors#mos'
     get "customer_faq" => "visitors#faq"
     get "partner_faq"  => "visitors#faq2"
     get "about"  => "visitors#about"
     # devise_for :users
     # devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
     resources :users
        resources :orders do 
       collection do 
        get :open
      end
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :order
  belongs_to :defect
  has_many :photos, as: :photoable, dependent: :destroy


  default_scope { order('due_date') }

end 
 

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.order_id = params[:order_id]
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to order_url(@item.order_id), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to order_url(@item.order_id), notice: 'Holding was successfully destroyed.' }

      #format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
      @photoable = @item
      @photos = @photoable.photos 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:order_id, :defect_id, :location, :followup, :due_date, :responsible_person, :completion_date, :remarks)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_after_photo_upload.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <!--    
      <div class="panel-heading">
        Photos
      </div>
      --> 

      <div style="padding:0" class="panel-body">
        <div style="padding:0" class="container">
          <div class="row">
            <div class="col-md-12">
              <!-- Phgotos upload goes here -->
              <%= form_for @item, url: create_after_item_photos_path(@item), method: 'post',
                  html: {multipart: true} do |f| %>

                 <div class="text-center">
                   <div class="form-group">

                     <span class="btn btn-info text-babu">
                       <i class="fa fa-camera" aria-hidden="true"></i><%= t("after_photos") %>
                       <%= file_field_tag "images[]", type: :file, multiple: true %>
                     </span>
                   </div>
                 </div>

                <div class="text-center">
                  <%= button_tag type: 'submit', class: "btn btn-primary" do %><%= t("upload") %>
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                  <% end %>
                </div>

              <% end %>
            </div>
          </div>

            <div id="after_photos"><%= render 'photos/item_after_photos_list' %> </div>


        </div>
      </div>

    </div>
  </div>

</div>

app/views/items/_before_photo_upload.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <!--    
      <div class="panel-heading">
        Photos
      </div>
      -->

      <div style="padding:0" class="panel-body">
        <div style="padding:0" class="container">
          <div class="row">
            <div class="col-md-12">
              <!-- Phgotos upload goes here -->
              <%= form_for @item, url: create_before_item_photos_path(@item), method: 'post',
                  html: {multipart: true} do |f| %>

                 <div class="text-center">
                   <div class="form-group">

                     <span class="btn btn-info  text-babu">
                       <i class="fa fa-camera" aria-hidden="true"></i><%= t("before_photos") %>
                       <%= file_field_tag "images[]", type: :file, multiple: true %>
                     </span>
                   </div>
                 </div>

                <div class="text-center">
                  <%= button_tag type: 'submit', class: "btn btn-primary" do %><%= t("upload") %>
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                  <% end %>
                </div>

              <% end %>
            </div>
          </div>

            <div id="before_photos"><%= render 'photos/item_before_photos_list' %> </div>

        </div>
      </div>

    </div>
  </div>

</div>

app/views/items/_form.html.erb
<div class="container">
  <%= simple_form_for(@item) do |f| %>

  <br>
    <div class="form-inputs">
      <%#= f.association :order %>
      <%= f.input :order_id, :value => params[:order_id] %>

        <div class="row">
            <div class="col-xs-12 col-md-4 ">
              <%= f.association :defect, label: t("defect") %>
            </div>
            <div class="col-xs-12 col-md-4 ">
              <%= f.input :location , label: t("location")%>
            </div>
            <div class="col-xs-12 col-md-4 ">
              <%= f.input :followup , label: t("followup")%>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-md-4 ">
              <%= f.input :due_date, as:  :datetime_picker, label: t("due_date")%>
            </div>
            <div class="col-xs-12 col-md-4 ">
              <%= f.input :completion_date, as:  :datetime_picker, label: t("completion_date") %>
            </div>
            <div class="col-xs-12 col-md-4 ">
              <%= f.input :responsible_person, label: t("responsible_person") %>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-md-12 ">
              <%= f.input :remarks, label: t("remarks") %>
            </div>
        </div>

    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/items/_photo_upload.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default"> 

      <div style="padding:0" class="panel-body">
        <div style="padding:0" class="container">  
          <div class="row"> 
            <div class="col-md-12">
              <!-- Phgotos upload goes here -->
              <%= form_for @item, url: create_general_item_photos_path(@item), method: 'post',
                  html: {multipart: true} do |f| %>

                 <div class="text-center">
                   <div class="form-group">

                     <span class="btn btn-info  text-babu">
                       <i class="fa fa-camera" aria-hidden="true"></i> <%= t("photos") %>
                       <% if @item.order.Open? or current_user.Admin? %>
                        <%= file_field_tag "images[]", type: :file, multiple: true %>
                       <% end %>
                     </span>
                   </div>
                 </div>

                <% if @item.order.Open? or current_user.Admin? %>
                  <div class="text-center">
                    <%= button_tag type: 'submit', class: "btn btn-primary" do %><%= t("upload") %>
                        <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                    <% end %>
                  </div>
                <% end %>
 

              <% end %>
            </div>
          </div>

            <div id="uploaded_photos"><%= render 'photos/item_photos' %> </div>           

        </div>
      </div>

    </div>
  </div>
</div>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Defect</th>
      <th>Location</th>
      <th>Followup</th>
      <th>Due date</th>
      <th>Responsible person</th>
      <th>Completion date</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.order %></td>
        <td><%= item.defect %></td>
        <td><%= item.location %></td>
        <td><%= item.followup %></td>
        <td><%= item.due_date %></td>
        <td><%= item.responsible_person %></td>
        <td><%= item.completion_date %></td>
        <td><%= item.remarks %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<%= render 'form' %>

app/views/items/show.html.erb
<div class="container">
      <br>
  <p>
    <strong><%= t("defect")%>:</strong>
    <%= @item.defect.display_name %>
  </p>

  <p>
    <strong><%= t("location")%>:</strong>
    <%= @item.location %>
  </p>

  <p>
    <strong><%= t("followup")%>:</strong>
    <%= @item.followup %>
  </p>

  <p>
    <strong><%= t("due_date")%>:</strong>
    <%= @item.due_date %>
  </p>

  <p>
    <strong><%= t("responsible_person")%>:</strong>
    <%= @item.responsible_person %>
  </p>

  <p>
    <strong><%= t("completion_date")%>:</strong>
    <%= @item.completion_date %>
  </p> 

  <p>
    <strong><%= t("remarks")%>:</strong>
    <%= @item.remarks %>
  </p>

  <%= link_to order_path(@item.order_id)  do %>
    <i class="glyphicon glyphicon-backward"></i>
  <% end %>
  <%= link_to edit_item_path(@item)  do %>
    <i class="glyphicon glyphicon-edit"></i>
  <% end %>
  <%= link_to @item, method: :delete, data: { confirm: 'Are you sure?' } do %>
    <i class="glyphicon glyphicon-trash"></i>
  <% end %>
  <%= render 'before_photo_upload' %> 
  <%= render 'after_photo_upload' %>
  <%= render 'photo_upload' %>
</div>
  <div id="photo_details"><%= render 'photos/item_photo_details' %> </div>