config/routes.rb
Rails.application.routes.draw do
  resources :order_parties
  resources :order_parties
  resources :defects
  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'auth/:provider/callback', to: 'sessions#create'
  get  'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  scope "(:locale)", locale: /en|zh/ do

    resources :items do  
        resources :photos, only: [:create, :destroy] do
          collection do
            post :create_general     #-> domain.com/orders/:id/acknowledge
            post :create_before     #-> domain.com/orders/:id/acknowledge
            post :create_after     #-> domain.com/orders/:id/acknowledge
            post :insert                #-> domain.com/orders/:id/acknowledge
          end
          member do
            put  :switch_printable     #-> domain.com/orders/:id/delete+photo
          end
        end
      end
      
    resources :defects
    resources :issues
    resources :defects
    resources :sources
    resources :districts
    resources :orders do  
        member do
          put :cancel         #-> domain.com/orders/:id/complete
          put :file        #-> domain.com/complaints/:id/escalate 
        end
        resource :downloadpdf, only: [:show] 
        resources :comments
        collection do
          match 'search' => 'orders#search', via: [:get, :post], as: :search
        end
        # collection { post :search, to: 'orders#search' }
        resources :photos, only: [:create, :destroy] do
          collection do
            post :create_general     #-> domain.com/orders/:id/acknowledge
            post :create_before     #-> domain.com/orders/:id/acknowledge
            post :create_after     #-> domain.com/orders/:id/acknowledge
            post :insert                #-> domain.com/orders/:id/acknowledge
          end
          member do
            put  :switch_printable     #-> domain.com/orders/:id/delete+photo
          end
        end
      end

     # mount Upmin::Engine => '/admin'
	 # root to: 'visitors#index' 
     root to: 'visitors#mos'
     get "customer_faq" => "visitors#faq"
     get "partner_faq"  => "visitors#faq2"
     get "about"  => "visitors#about"
     # devise_for :users
     # devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
     resources :users
        resources :orders do 
       collection do 
        get :open
      end
    end
  end
end

app/views/layouts/_devise_errors.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="container">
  <hr>
  <footer>
      <div class="row">
          <div class="col-lg-12 text-center ">
              <p>Copyright &copy; <%= t("brand") %> 2016</p>
          </div>
      </div>
  </footer>
</div>
<!-- /.container -->

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/layouts/_mpage.html.erb
<div>
    <%= link_to @order  do %>
      <i class="glyphicon glyphicon-zoom-in btn btn-tall btn-grey fa-2x col-xs-6"></i> 
    <% end %>
    <%= link_to orders_path  do %>
      <i class="glyphicon glyphicon-list  btn btn-tall btn-success fa-2x col-xs-6"></i>
    <% end %>
</div>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('account')%><b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to t('edit_account'), edit_user_registration_path %></li>
          <li><%= link_to t('sign_out'), destroy_user_session_path, :method=>'delete' %></li>
	  <% if current_user.try(:Admin?) %>
	    <li><%= link_to t('admin'), users_path %></li>
	  <% end %>
        </ul>
    </li>
<% else %>
  <li><%#= link_to t('sign_in'), new_user_session_path %></li>
  <li><%#= link_to t('sign_up'), new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('home'), root_path, class: 'navbar-brand' %> 
      <div class="nav-bar-left">
      <%#= link_to root_url do %>
        <%#= image_tag "FirstLogo.jpg", :size => "50x50" %>
      <%# end %>
      </div>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>

  <% if current_user.Admin? and !mobile_device? %>
        <li class="nav-item dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('administration')%><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t('issues_list'), issues_path %></li>
              <li><%= link_to t('defects_list'), defects_path %></li>
              <li><%= link_to t('district_list'), districts_path %></li>
            </ul>
        </li>
  <% end %>

        <% if !mobile_device? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('report')%><b class="caret"></b></a>
              <ul class="dropdown-menu">            
                <li><%= link_to t('NewReport'), new_order_path %></li>
                <li><%= link_to t('ReportLists'), orders_path(:status => "Open") %></li>
                <!--
                <li><%= link_to t('RearchReport'), search_orders_path(:commit => "Search") %> </li>  
                -->              
              </ul>
          </li>
        <% end %>
  <%# else %> 
      <li><%#= link_to t('order_list'), orders_path %></li> 

<% else %>
    <li><%= link_to t('FAQ'), customer_faq_path %></li>
    <li><%#= link_to t('about'), about_path %></li>
<% end %>   

<% if I18n.locale == :zh %>
    <li><%= link_to 'Eng', url_for( :locale => 'en' ) %></li>    
<% else %>
    <li><%= link_to '中文', url_for( :locale => 'zh' ) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="mobile-web-app-capable" content="yes">
    <title><%= t("app_title") %></title>
    <meta name="description" content="<%= t("app_desc") %>">
    <link rel="icon" type="image/jpg" href="/assets/RoadReportHK.jpg">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyArUITXOOtiOjuqpPAFEAZRiWv15lOuIVE&libraries=places"></script>
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_include_tag "https://www.gstatic.com/firebasejs/3.6.1/firebase.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts Google tracker code = UA-118278120-1-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="manifest" href="/manifest.json" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= analytics_init if GoogleAnalytics.valid_tracker? %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/messages' %>
    

        <%= yield %>
    
    <% if !mobile_device? %>
    <% then %>
      <%= render 'layouts/footer' %>l
    <% end %> 
    
  </body>
  
</html>

app/views/layouts/complaint_pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Complaint Report</title>
  <style>
    <%= Rails.application.assets.find_asset('application.scss').to_s %>
  </style>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/order_pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Order Report</title>
  <style>
    <%= Rails.application.assets.find_asset('application.scss').to_s %>
  </style>
</head>
<body>
  <%= yield %>
</body>
</html>